### ISSUE TITLE
Data visualisation

### ISSUE THREAD

**Issue by WikGitHub** [kaist-amsg/Composition-Conditioned-Crystal-GAN#2]

**Comment by sgbaird** [comment]
@WikGitHub Shot in the dark here. Did you try the following function:
https://github.com/kaist-amsg/Composition-Conditioned-Crystal-GAN/blob/35cf6d0a51a272262d3efbd8f242381390d59c34/Composition_Conditioned_Crystal_GAN/view_atoms_mgmno.py#L63-L76

where [you load the `.npy` file](https://numpy.org/doc/stable/reference/generated/numpy.load.html) and pass that array as the `image` argument?

**Comment by WikGitHub** [comment]
Thanks Sterling! So that code produces the unit cell + atoms in an ase-gui window. I'm looking to then from this create the folded protein structures.

**Comment by sgbaird** [comment]
@WikGitHub ah, gotcha. I'm totally out of my element there. Did some simple Google searches but not much luck. Are you sure that the `.npy` files contain information related to protein structure? I figured `Composition-Conditioned-Crystal-GAN` was just for crystal structure. Maybe there's some way to infer protein structure from a collection of atoms and atom locations.

**Comment by WikGitHub** [comment]
@sgbaird if you see this link https://people.cs.vt.edu/dbhattacharya/courses/cs6824/Paper2.pdf, the pipeline (slide 8) shows the usage of heat maps generated from atom locations to infer protein structure, this is either done via ADMM or Rosetta.

**Comment by sgbaird** [comment]
Ok gotcha. You might have better luck looking at [ADMM](https://github.com/bhushan23/ADMM) or [Rosetta](https://github.com/RosettaCommons/RoseTTAFold) repos and asking there if you get stuck.
